# Generated by Django 3.2.16 on 2025-01-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_group_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
