# Generated by Django 3.2.16 on 2025-01-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20250119_1404'),
        ('posts', '0003_alter_post_text'),
    ]

    operations = [
    ]
